### ISSUE TITLE
Add your ideas for automation of tasks

### ISSUE THREAD

**Issue by ZoranPandovski** [AAYBS/suggestion-box#1]
# Suggestion :see_no_evil: :hear_no_evil: :speak_no_evil: Box

# :bulb: Ideas :bulb:
* Have a great idea? 
* You need to automate some of your boring stuff?

Just create an [issue](https://github.com/AAYBS/suggestion-box/issues/new) with the description and together we can build it !!!

# :checkered_flag: Start :checkered_flag:

If you don't know where to start check this awesome book:
https://automatetheboringstuff.com/

**Comment by ananya218** [comment]
Hey there,I guess I have some ideas regarding your automation of tasks,which I'd like to share.You can see if it's in your interest.

**Comment by ZoranPandovski** [comment]
@ananya218 Sure, just open a new issue and we can discuss there. Regards
